name: libnl-tiny

on:
  pull_request:
  push:

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            gcc: /usr/bin/aarch64-linux-gnu-gcc
            packages: gcc-aarch64-linux-gnu
          - arch: arm
            gcc: /usr/bin/arm-linux-gnueabi-gcc
            packages: gcc-arm-linux-gnueabi
          - arch: mips
            gcc: /usr/bin/mips-linux-gnu-gcc
            packages: gcc-mips-linux-gnu
          - arch: x86_64
            gcc: /usr/bin/x86_64-linux-gnu-gcc
            packages: gcc-x86-64-linux-gnu

    steps:
      - name: Checkout libnl-tiny
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt install ${{ matrix.packages }}

      - name: Prepare build
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/build

      - name: Build libnl-tiny
        run: |
          cmake \
            -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }} \
            -DCMAKE_C_COMPILER=${{ matrix.gcc }} \
            -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/build \
            --install-prefix ${GITHUB_WORKSPACE}/build
          make
          make install
